config/routes.rb
Rails.application.routes.draw do

   root 'welcome#index'
  get 'about', to: 'welcome#about'
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :name, presence: true, length: {minimum: 4, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 4, maximum: 12}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {minimum:20, maximum:105}, format: {with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
    end
    
    def show
       @article = Article.find(params[:id])
    end
    
    def new
        @article = Article.new
    end
    
    def create
       @article = Article.new(article_params)
       if @article.save
           flash[:success] = "Your article save sucessfully"
           redirect_to article_path(@article)
       else
           render 'new'
       end
    end
    
    def edit
       @article = Article.find(params[:id]) 
    end
    
    def update
       @article = Article.find(params[:id])
       if @article.update(article_params)
           flash[:success] = "Your article have sucessfully updated"
           redirect_to article_path(@article)
       else
           render 'edit'
       end
    end
    
    def destroy
       @article =Article.find(params[:id])
       @article.destroy
       flash[:success] = "Your article has been deleted"
       redirect_to articles_path
    end
    
    private
    def article_params
        params.require(:article).permit(:name, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        
    end
    
    def about
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="row">
    <div class="col-xs-12 col-md-offset-2">
<%= form_for(@article, :html=> {class: 'form-horizental', role: 'form' }) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-12">
            <%= f.label :Name %>
        </div>
        <div class="col-md-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Article Name" %>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-12">
            <%= f.label :Description %>
        </div>
        <div class="col-md-8">
            <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Article Body" %>
        </div>
    </div></br>
    <div class="form-group">
        <div class="control-label col-sm-12">
            <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
    </div>
<% end %>
<div class="form-group">
        <div class="control-label col-sm-12 col-md-offset-4">
[<%= link_to "Back to Articles", articles_path %>]
</div>
</div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Editing....</h1>

<%= render 'articles/form' %>

app/views/articles/index.html.erb
<h1 align="center">All Articles</h1>
<div class="center">
    <%= will_paginate %>
</div>

<% @articles.each do |article| %>
    <ul>
        <div class="well col-md-offset-2 col-md-8">
        <%= article.name %> </br>
        <%= truncate(article.description, length: 100) %>  </br>
        <small>
            <%= time_ago_in_words(article.created_at) %> ago
        </small> </br>
        <%= link_to "Show Articles", article_path(article), class: "btn btn-sm btn-default" %>
        <%= link_to "Edit Article", edit_article_path(article), class: "btn btn-sm btn-primary" %>
        <%= link_to "Delete Article", article_path(article),
                              method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-sm btn-danger"  %>
        </div>
    </ul>
<% end %>

app/views/articles/new.html.erb
<h1 align="center">Creating....</h1>

<%= render 'articles/form' %>

app/views/articles/show.html.erb
           <h2 align="center">Title: <%= @article.name %></h2>
    <ul>
        <div class="well col-md-offset-2 col-md-8">
        <strong>Description: </strong></br> <%= @article.description %>  </br>
        <small>
           <%= time_ago_in_words(@article.created_at) %> ago
        </small> </br>
        <%= link_to "Edit Article", edit_article_path(@article), class: "btn btn-sm btn-primary" %>
        <%= link_to "Delete Article", article_path(@article),
                              method: :delete, data: {confirm: "Are you sure"}, class: "btn btn-sm btn-danger"  %>
        </div>
    </ul>

app/views/layouts/_footer.html.erb
<div class="container">

<footer class="footer">

<small>

Copyright © <a href="enter in a link here">The Complete Ruby on Rails Developer</a>

by <a href="enter in a link here">Fahad Akhtar</a>

</small>

<nav>

<ul>

<li><%= link_to "About", about_path %></li>

</ul>

</nav>

</footer>

</div>

app/views/layouts/_message.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
      <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
      <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">

<div class="container-fluid">

<!-- Brand and toggle get grouped for better mobile display -->

<div class="navbar-header">

<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

<span class="sr-only">Toggle navigation</span>

<span class="icon-bar"></span>

<span class="icon-bar"></span>

<span class="icon-bar"></span>

</button>

<%= link_to "Beta blog", root_path, class: "navbar-brand", id: "logo" %>

</div>

<!-- Collect the nav links, forms, and other content for toggling -->

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

<ul class="nav navbar-nav">

<li><%= link_to "Articles", articles_path %></li>

<li><a href="#">Link</a></li>

<li class="dropdown">

<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>

<ul class="dropdown-menu">

<li><%= link_to "Create Article", new_article_path %></li>

<li><a href="#">Another action</a></li>

<li><a href="#">Something else here</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">Separated link</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">One more separated link</a></li>

</ul>

</li>

</ul>

<form class="navbar-form navbar-left" role="search">
  <div class="form-group">
  <input type="text" class="form-control" placeholder="Search">
  </div>
  <div class="form-group">
  <input type="text" class="form-control" placeholder="Search">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

<ul class="nav navbar-nav navbar-right">

<li><a href="#">Link</a></li>

<li class="dropdown">

<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>

<ul class="dropdown-menu">

<li><a href="#">Action</a></li>

<li><a href="#">Another action</a></li>

<li><a href="#">Something else here</a></li>

<li role="separator" class="divider"></li>

<li><a href="#">Separated link</a></li>

</ul>

</li>

</ul>

</div><!-- /.navbar-collapse -->

</div><!-- /.container-fluid -->

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beta Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/message' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(obj.errors.count, "error") %>
                        prohibited this article form being save:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>    
                            <% end %>
                         </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/welcome/about.html.erb
<h1>It's About Page</h1>

app/views/welcome/index.html.erb
<div class="center jumbotron">
    
    <%= link_to 'Sign Up Now', about_path, class: "btn btn-danger btn-lg btn-xlarge" %> 
</div>